# for module compiling
import os
Import('WM_ROOT')

Import('wmconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
if wmconfig.CROSS_TOOL == 'keil':
    LINKFLAGS = ' --keep *_entry '
else:
    LINKFLAGS = '' 

CPPPATH =CPPPATH + [WM_ROOT + '/boards/dq-sim900a']
CPPPATH =CPPPATH + [WM_ROOT + '/include']
# CPPPATH = CPPPATH + [WM_ROOT + '/libcpu/stm32/StdPeriph/inc']
# CPPPATH = CPPPATH + [WM_ROOT + '/libcpu/stm32/cmsis']
# CPPPATH = CPPPATH + [WM_ROOT + '/libcpu/ARM_CM3']
# CPPPATH = CPPPATH + [WM_ROOT + '/libcpu/cmsis']

group = DefineGroup('app', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS)

Return('group')
