import os
import sys
import wmconfig

if os.getenv('WM_ROOT'):
    WM_ROOT = os.getenv('WM_ROOT')
else:
    WM_ROOT = os.path.normpath(os.getcwd() + '/../..')

sys.path = sys.path + [os.path.join(WM_ROOT, 'tools')]
from building import *

TARGET = 'wmdp.' + wmconfig.TARGET_EXT

env = Environment(tools = ['mingw'],
	AS = wmconfig.AS, ASFLAGS = wmconfig.AFLAGS,
	CC = wmconfig.CC, CCFLAGS = wmconfig.CFLAGS,
	AR = wmconfig.AR, ARFLAGS = '-rc',
	LINK = wmconfig.LINK, LINKFLAGS = wmconfig.LFLAGS)
env.PrependENVPath('PATH', wmconfig.EXEC_PATH)

if wmconfig.PLATFORM == 'iar':
	env.Replace(CCCOM = ['$CC $CCFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS -o $TARGET $SOURCES'])
	env.Replace(ARFLAGS = [''])
	env.Replace(LINKCOM = ['$LINK $SOURCES $LINKFLAGS -o $TARGET --map wmdp.map'])

Export('WM_ROOT')
Export('wmconfig')

# prepare building environment
objs = PrepareBuilding(env, WM_ROOT, has_libcpu=False)


# make a building
DoBuilding(TARGET, objs)
