from building import *

cwd     = GetCurrentDir()
src     = ['read.c', 'write.c']
CPPPATH = ''
group   = DefineGroup('iar', src, depend = ['CONFIG_REDIRECT_STDIO'], CPPPATH = CPPPATH)

Return('group')
