# for module compiling
Import('DDDP_ROOT')
Import('dddp_config')
import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if item == dddp_config.CPU:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            objs = objs + SConscript(os.path.join(item, 'SConscript'))
if os.path.isfile(os.path.join(cwd, "arm_cm3", 'SConscript')):
    objs = objs + SConscript(os.path.join("arm_cm3", 'SConscript'))

Return('objs')
