Import('wmconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('STM32_Driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
