Import('wmconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
src     =['device.c', 'ringbuf.c', 'console.c']
CPPPATH = [cwd]

group = DefineGroup('common', src, depend = ['CONFIG_USING_COMMON'], CPPPATH = CPPPATH)

Return('group')
