Import('wmconfig')
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
if wmconfig.CROSS_TOOL == 'keil':
    src     = Glob('*_keil.s')
elif wmconfig.CROSS_TOOL == 'iar':
    src     = Glob('*_iar.s')
else :
    LINKFLAGS = ''

group = DefineGroup('ARM_CM3', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
