# for module compiling
Import('WM_ROOT')
Import('wmconfig')
import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if item == wmconfig.ARCH:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
